### ISSUE TITLE
Theming is missing

### ISSUE THREAD

**Issue by Cediddi** [ivocavalcante/PrusaSlicer-snap#1]
I've just started using this build. From what I see, theming is missing. How can I help you about this issue?

![Screenshot_20201105_143116](https://user-images.githubusercontent.com/2720608/98235934-936c9900-1f73-11eb-9b81-8bdc2f9aada7.png)

**Comment by ivocavalcante** [comment]
Hi @Cediddi , thanks for reporting.

Could you please provide more info? Linux distribution, snap version, theme you're using, for instance.

**Comment by ivocavalcante** [comment]
I uploaded a new version; can you try it, please?

**Comment by ivocavalcante** [comment]
Hello @Cediddi , any feedback on this?

**Comment by Cediddi** [comment]
I'm sorry for late reply.

> Linux distribution, snap version, theme you're using, for instance.
snap    2.47.1+18.04
snapd   2.47.1+18.04
series  16
ubuntu  18.04
kernel  5.4.0-48-generic
plasmashell 5.12.9

Theme: Materia Dark [KDE], Breeze-Dark [GTK2/3]

**Comment by Cediddi** [comment]
Problem persists with edge branch + a new issue of ssl certs

![Screenshot_20201117_171513](https://user-images.githubusercontent.com/2720608/99400861-8b5c1400-28f8-11eb-969e-8c9931e061ea.png)
![Screenshot_20201117_171501](https://user-images.githubusercontent.com/2720608/99400865-8d25d780-28f8-11eb-8ca8-8271cb6a12c4.png)

**Comment by ivocavalcante** [comment]
Ok @Cediddi , let's go:

The message about SSL is not an issue, it comes with 2.3.0 version of the app, even on the AppImage they build and provide themselves. It's just an information and most people would safely click "Remember my choice" and go on.

As for the theming, need some more info. Could you, please, provide the output of commands below?

`snap info prusa-slicer | grep installed:`

and

`snap connections prusa-slicer`

**Comment by Cediddi** [comment]
For stable package, this are the outputs:
```
cediddi@aiur:~$ snap info prusa-slicer|grep installed:
installed:          2.2.0-snap2                   (13) 162MB -
cediddi@aiur:~$ snap connections prusa-slicer 
Interface               Plug                           Slot                              Notes
content[gtk-2-engines]  prusa-slicer:gtk-2-engines     gtk2-common-themes:gtk-2-engines  -
content[gtk-2-themes]   prusa-slicer:gtk-2-themes      gtk-common-themes:gtk-2-themes    -
content[icon-themes]    prusa-slicer:icon-themes       gtk-common-themes:icon-themes     -
content[sound-themes]   prusa-slicer:sound-themes      gtk-common-themes:sound-themes    -
desktop                 prusa-slicer:desktop           :desktop                          -
desktop-legacy          prusa-slicer:desktop-legacy    :desktop-legacy                   -
hardware-observe        prusa-slicer:hardware-observe  -                                 -
home                    prusa-slicer:home              :home                             -
mount-observe           prusa-slicer:mount-observe     -                                 -
network                 prusa-slicer:network           :network                          -
opengl                  prusa-slicer:opengl            :opengl                           -
optical-drive           prusa-slicer:optical-drive     :optical-drive                    -
raw-usb                 prusa-slicer:raw-usb           -                                 -
removable-media         prusa-slicer:removable-media   -                                 -
unity7                  prusa-slicer:unity7            :unity7                           -
wayland                 prusa-slicer:wayland           :wayland                          -
x11                     prusa-slicer:x11               :x11                              -
```

And for the edge version, outputs goes like this:
```
cediddi@aiur:~$ snap info prusa-slicer|grep installed:
installed:          2.3.0-alpha3-snap1            (16) 259MB -
cediddi@aiur:~$ snap connections prusa-slicer         
Interface               Plug                           Slot                              Notes
content[gtk-2-engines]  prusa-slicer:gtk-2-engines     gtk2-common-themes:gtk-2-engines  -
content[gtk-2-themes]   prusa-slicer:gtk-2-themes      gtk-common-themes:gtk-2-themes    -
content[icon-themes]    prusa-slicer:icon-themes       gtk-common-themes:icon-themes     -
content[sound-themes]   prusa-slicer:sound-themes      gtk-common-themes:sound-themes    -
desktop                 prusa-slicer:desktop           :desktop                          -
desktop-legacy          prusa-slicer:desktop-legacy    :desktop-legacy                   -
hardware-observe        prusa-slicer:hardware-observe  -                                 -
home                    prusa-slicer:home              :home                             -
mount-observe           prusa-slicer:mount-observe     -                                 -
network                 prusa-slicer:network           :network                          -
opengl                  prusa-slicer:opengl            :opengl                           -
optical-drive           prusa-slicer:optical-drive     :optical-drive                    -
raw-usb                 prusa-slicer:raw-usb           -                                 -
removable-media         prusa-slicer:removable-media   -                                 -
unity7                  prusa-slicer:unity7            :unity7                           -
wayland                 prusa-slicer:wayland           :wayland                          -
x11                     prusa-slicer:x11               :x11                              -
```

**Comment by ivocavalcante** [comment]
Ok, installed Kubuntu 18.04 in a VM and reproduced the issue. I'll take a look at it.

**Comment by ivocavalcante** [comment]
The problem is that GTK uses Xsettings protocol to define/query themes and other properties; KDE doesn't use it, resorting to the ~/.gtkrc-2.0 file (this is what you change when use KDE GTK interface), and strictly confined Snaps (as PrusaSlicer Snap) can't access these by default. I'll take the case to Snap forum, see if anyone has a solution but, for now, you can copy the file to snap home and it'll work:
```
cp ~/.gtkrc-2.0 ~/snap/prusa-slicer/current/
```

You'll have to do it everytime you change GTK definitions on KDE interface (linking doesn't work also, 'cause of confinement).
I'll let you know if/when I have a definitive solution.

Please, let me know if this _solves_ your problem for now.

**Comment by ivocavalcante** [comment]
Hello @Cediddi ,

Just released new beta version, GTK 3 based (was using GTK 2 'till alpha3, due to bugs on the UI). Tested this version on Kubuntu 18.04 and it seems to get themes right. Could you try this one, please?

**Comment by Cediddi** [comment]
Exceptional work, thank you. 
![Screenshot_20201130_134207](https://user-images.githubusercontent.com/2720608/100600069-db33d580-3311-11eb-8e1c-2671149802e0.png)
