### ISSUE TITLE
Wrong GTK_USE_PORTAL naming

### ISSUE THREAD

**Issue by seb128** [ivocavalcante/PrusaSlicer-snap#2]
The correct variable is GTK_USE_PORTAL (singular), that's similar to https://github.com/snapcore/snapcraft/pull/3356/

**Comment by ivocavalcante** [comment]
Hi @seb128 , thanks for reporting. I'll look into it.

**Comment by ivocavalcante** [comment]
Fixed on stable and edge releases.
