### ISSUE TITLE
Programm crashes on importing configuration

### ISSUE THREAD

**Issue by akira25** [ivocavalcante/PrusaSlicer-snap#4]
On current version 2.3.1+snap1 I had observed this behavoir:

Everytime I click on the entry "import a configuration bundle" the programm closes immediately. This happens for the other entries on importing configuration too. There appears no file dialog, but the programm just closes.

I experienced this on recent kubuntu 20.04 LTS.

**Comment by ivocavalcante** [comment]
Thanks for reporting. I was able to reproduce the issue, will look into it.

**Comment by ivocavalcante** [comment]
Fixed on new release, 2.3.1+snap2. Please update and report back, if you encounter any issues. Thanks again.
