### ISSUE TITLE
Can't access /dev/ttyACM0 in Ubuntu 20.04

### ISSUE THREAD

**Issue by Jebtrix** [ivocavalcante/PrusaSlicer-snap#7]
Saw this issue come up on Prusaslicer but its for you. 

https://github.com/prusa3d/PrusaSlicer/issues/7882

You are missing avrdude-slic3r in snapcraft.yaml

**Comment by ivocavalcante** [comment]
Hi! Thanks for pointing out.

**Comment by ivocavalcante** [comment]
Snap store listing was updates, including instructions on how to connect interface needed to allow firmware upgrade.
