### ISSUE TITLE
Slicer closes when trying to import model from secondary drive

### ISSUE THREAD

**Issue by danblae** [ivocavalcante/PrusaSlicer-snap#8]
Hey,

I am using Kubuntu and I have a secondary hard drive, which is encrypted and gets automatically decrypted and mounted when I decrypt the primary drive with the operating system (Maybe that information is useful). 

Here to the actual problem and the info I have. When I try to add a model as usual and click on my secondary drive in the file explorer, the slicer just closes. I have also started the slicer via a terminal and got the following error message:

```
GLib-GIO:ERROR:../../../gio/gunixvolume.c:324:eject_mount_do: assertion failed (error == NULL): Failed to execute child process “mount” (Permission denied) (g-exec-error-quark, 3)
Bail out! GLib-GIO:ERROR:../../../gio/gunixvolume.c:324:eject_mount_do: assertion failed (error == NULL): Failed to execute child process “mount” (Permission denied) (g-exec-error-quark, 3)
Aborted (core dumped)

```
Is there a way I can fix this or is there a workaround for this issue?

**Comment by ivocavalcante** [comment]
Hi danblae,

I need some more info. Where is the volume mounted? Also, do you see any apparmor message on `/var/log/syslog` when error happens?

Edit: you don't need to tell the mountpoint path exactly if you don't want, just say if it's inside `/home`, `/run/user` or `/mnt`, for instance.

**Comment by danblae** [comment]
[syslog.log](https://github.com/ivocavalcante/PrusaSlicer-snap/files/8059106/syslog.log)

And for the mount point, I have it mounted on `/` I know this is not a good practice, but I had something else that did not want to work with the drive mounted anywhere else.

(But I did make sure the permissions are set accordingly and that my user is owner of the drive.)

**Comment by ivocavalcante** [comment]
Thanks for the info.

Are you, by chance, running PrusaSlicer as root? Or, have you mounted your external drive as root user (and not using udisks, for instance) ?

Also, could you, please, tell what Snap version are you using?   (`snap info prusa-slicer | grep ^installed`)

**Comment by danblae** [comment]
2.4.0+snap2

And no, running Prusa slicer as root is not possible. I have tried, but it won't start as root because of temporary folders in directories it is not allowed to access.

And the ownership of the external drive is set to the user I am executing prusa-slicer with. I am not 100% sure if the drive is getting mounted by root, but I doubt it. I have to check that when I have access to the device again,

**Comment by danblae** [comment]
Ok, I was wrong, the folder gets mounted by root, but it is accessible through any other application I have.

**Comment by ivocavalcante** [comment]
Ok danblae, will try to reproduce tomorrow. Will let you know if I need more info.

**Comment by danblae** [comment]
Thanks, I appreciate it!

**Comment by ivocavalcante** [comment]
Closing since it's been inactive for so long that I don't believe it s valid anymore.
